import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

const Navbar: React.FC = () => {
  return (
    <nav>
      <Link href={"/"}>Home</Link>
      <Link href={"/projects"}>Projects</Link>
    </nav>
  );
};
